blueprint: ## Generate all blueprints file
	@if ! type orbit >/dev/null 2>&1; then echo "Missing orbit dependency, please install from https://github.com/gulien/orbit/"; exit 1; fi
	orbit run generate
	@gsed -i '1i\# DO NOT EDIT THIS FILE : Make yours changes in /utils/Dockerfile.*.blueprint)' Dockerfile.*
	@gsed -i '1i\[DO NOT EDIT THIS FILE]: <> (Make yours changes in /utils/README.blueprint.md)' README.md

test-latest: test-8.4 ## Test the latest build only

_test-prerequisites: blueprint
	docker pull ubuntu:noble

test-quick: _test-prerequisites ## Test 8.4 and 8.3 quickly
	PHP_VERSION=8.4 BRANCH=v8 VARIANT=cli OWNER="qonstrukt" PLATFORM="linux/`uname -p`64" ./build-and-test.sh || (echo "Tests failed" && exit 1)
	PHP_VERSION=8.3 BRANCH=v8 VARIANT=cli OWNER="qonstrukt" PLATFORM="linux/`uname -p`64" ./build-and-test.sh || (echo "Tests failed" && exit 1)
	echo "Tests passed with success"

test-8.4: _test-prerequisites ## Test php8.4 build only
	PHP_VERSION=8.4 BRANCH=v8 VARIANT=cli OWNER="qonstrukt" PLATFORM="linux/`uname -p`64" ./build-and-test.sh || (echo "Tests failed" && exit 1)
	PHP_VERSION=8.4 BRANCH=v8 VARIANT=apache OWNER="qonstrukt" PLATFORM="linux/`uname -p`64" ./build-and-test.sh || (echo "Tests failed" && exit 1)
	echo "Tests passed with success"

test-8.3: _test-prerequisites ## Test php8.3 build only
	PHP_VERSION=8.3 BRANCH=v8 VARIANT=cli OWNER="qonstrukt" PLATFORM="linux/`uname -p`64" ./build-and-test.sh || (echo "Tests failed" && exit 1)
	PHP_VERSION=8.3 BRANCH=v8 VARIANT=apache OWNER="qonstrukt" PLATFORM="linux/`uname -p`64" ./build-and-test.sh || (echo "Tests failed" && exit 1)
	echo "Tests passed with success"

test-8.2: _test-prerequisites ## Test php8.2 build only
	PHP_VERSION=8.2 BRANCH=v8 VARIANT=cli OWNER="qonstrukt" PLATFORM="linux/`uname -p`64" ./build-and-test.sh || (echo "Tests failed" && exit 1)
	PHP_VERSION=8.2 BRANCH=v8 VARIANT=apache OWNER="qonstrukt" PLATFORM="linux/`uname -p`64" ./build-and-test.sh || (echo "Tests failed" && exit 1)
	echo "Tests passed with success"

clean: ## Clean dangles image after build
