name: Docker PHP Images GitHub workflow

on:
  pull_request:
    branches:
      - 'v4'
  push:
    branches:
      - 'v4'

jobs:
  build_test_maybe_release:
    strategy:
      matrix:
        php_version: ['7.4']
        # php_version: ['7.2', '7.3', '7.4', '8.0', '8.1']
        platform: ['linux/arm64']
        # platform: ['linux/amd64', 'linux/arm64']
        variant: ['cli', 'fpm']
        # variant: ['apache', 'cli', 'fpm']
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1
      - name: Build and test
        run: |
          PHP_VERSION="${{ matrix.php_version }}" BRANCH="v4" PLATFORM="${{ matrix.platform }}" VARIANT="${{ matrix.variant }}" ./build-and-test.sh
      - name: Login to DockerHub
        # Merge ~ push.
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release
        # Merge ~ push.
        if: ${{ github.event_name == 'push' }}
        run: |
          BRANCH_VARIANT=`echo "${{ matrix.variant }}" | sed 's/\./-/g'`
          docker push thecodingmachine/php:${{ matrix.php_version }}-v4-slim-${BRANCH_VARIANT}
          docker push thecodingmachine/php:${{ matrix.php_version }}-v4-${BRANCH_VARIANT}
          docker push thecodingmachine/php:${{ matrix.php_version }}-v4-${BRANCH_VARIANT}-node14
          # Let's also tag PHP patch releases
          PHP_PATCH_VERSION=`docker run --rm thecodingmachine/php:${{ matrix.php_version }}-v4-slim-${BRANCH_VARIANT} php -v | head -n1 | grep -P '\d+\.\d+\.\d+' -o | head -n1`
          echo "Tagging patch release $PHP_PATCH_VERSION"
          docker tag thecodingmachine/php:${{ matrix.php_version }}-v4-slim-${BRANCH_VARIANT} thecodingmachine/php:${PHP_PATCH_VERSION}-v4-slim-${BRANCH_VARIANT}
          docker tag thecodingmachine/php:${{ matrix.php_version }}-v4-${BRANCH_VARIANT} thecodingmachine/php:${PHP_PATCH_VERSION}-v4-${BRANCH_VARIANT}
          docker tag thecodingmachine/php:${{ matrix.php_version }}-v4-${BRANCH_VARIANT}-node14 thecodingmachine/php:${PHP_PATCH_VERSION}-v4-${BRANCH_VARIANT}-node14
          docker push thecodingmachine/php:${PHP_PATCH_VERSION}-v4-slim-${BRANCH_VARIANT}
          docker push thecodingmachine/php:${PHP_PATCH_VERSION}-v4-${BRANCH_VARIANT}
          docker push thecodingmachine/php:${PHP_PATCH_VERSION}-v4-${BRANCH_VARIANT}-node14
